"""empty message

Revision ID: 046c7ccab190
Revises: 00f1cc11a882
Create Date: 2023-05-13 13:36:58.216757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046c7ccab190'
down_revision = '00f1cc11a882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_movie_fav', ['user_id', 'movie_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_movie_fav', type_='unique')

    # ### end Alembic commands ###
