"""empty message

Revision ID: 1add03f367a3
Revises: c79596f583a2
Create Date: 2023-05-11 11:24:10.572258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1add03f367a3'
down_revision = 'c79596f583a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_movie_id'), ['movie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_rate'), ['rate'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_rate'))
        batch_op.drop_index(batch_op.f('ix_rating_movie_id'))

    op.drop_table('rating')
    # ### end Alembic commands ###
