"""empty message

Revision ID: 57f24244d53a
Revises: bdf340334bc6
Create Date: 2023-05-12 17:10:52.714588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f24244d53a'
down_revision = 'bdf340334bc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_comment_created'), ['created'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_comment_created'))

    op.drop_table('post_comment')
    # ### end Alembic commands ###
