"""empty message

Revision ID: 613e096d1e8f
Revises: 046c7ccab190
Create Date: 2023-05-13 16:11:02.800926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613e096d1e8f'
down_revision = '046c7ccab190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_user_id'))

    # ### end Alembic commands ###
