"""empty message

Revision ID: 6a7fa6a6493a
Revises: 1add03f367a3
Create Date: 2023-05-11 11:49:49.186577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a7fa6a6493a'
down_revision = '1add03f367a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_index('ix_rating_movie_id')
        batch_op.create_index(batch_op.f('ix_rating_movie_id'), ['movie_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_movie_id'))
        batch_op.create_index('ix_rating_movie_id', ['movie_id'], unique=False)

    # ### end Alembic commands ###
