"""empty message

Revision ID: c79596f583a2
Revises: 9e6d1e639d6c
Create Date: 2023-05-10 17:30:42.767469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79596f583a2'
down_revision = '9e6d1e639d6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_movie_id'), ['movie_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_movie_id'))
        batch_op.drop_column('movie_id')

    # ### end Alembic commands ###
