# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUser():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_user(self):
    self.driver.get("http://localhost:5000/")
    self.driver.set_window_size(686, 806)
    self.driver.find_element(By.LINK_TEXT, "Now Playing").click()
    self.driver.find_element(By.LINK_TEXT, "Top Rated").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("Test")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Test")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.LINK_TEXT, "Register").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("Test")
    self.driver.find_element(By.ID, "email").send_keys("test@test.wp.pl")
    self.driver.find_element(By.ID, "password").send_keys("test")
    self.driver.find_element(By.ID, "password2").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-12:nth-child(1)").click()
    self.driver.find_element(By.NAME, "q").click()
    self.driver.find_element(By.NAME, "q").send_keys("avengers")
    self.driver.find_element(By.NAME, "q").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Show more").click()
    self.driver.find_element(By.ID, "favorite").click()
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "rate").send_keys("3")
    self.driver.find_element(By.ID, "rate").click()
    self.driver.find_element(By.ID, "submit").click()
    self.driver.find_element(By.ID, "body").click()
    self.driver.find_element(By.ID, "body").send_keys("Good one")
    self.driver.find_element(By.CSS_SELECTOR, "form > #submit").click()
    self.driver.find_element(By.LINK_TEXT, "Today on TV").click()
    self.driver.find_element(By.LINK_TEXT, "Test").click()
    self.driver.find_element(By.LINK_TEXT, "List of favorite movies (1 movies)").click()
    self.driver.find_element(By.LINK_TEXT, "Test").click()
    self.driver.find_element(By.LINK_TEXT, "All posts (1)").click()
    self.driver.find_element(By.LINK_TEXT, "Good one").click()
    self.driver.find_element(By.ID, "body").click()
    self.driver.find_element(By.ID, "body").send_keys("Comment")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.LINK_TEXT, "Test").click()
    self.driver.find_element(By.LINK_TEXT, "All rated movies (1)").click()
    self.driver.find_element(By.LINK_TEXT, "Show more").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.close()
  
