# Generated by Selenium IDE
import random
import string
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUser():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
    self.data = self.random_register_data()

  def teardown_method(self, method):
    self.driver.quit()

  def random_register_data(self):
    return (''.join(random.choices(string.ascii_uppercase + string.digits, k=8)))

  
  def test_user(self):
    self.driver.get("http://localhost:5000/")
    self.driver.set_window_size(686, 806)
    self.driver.find_element(By.LINK_TEXT, "Now Playing").click()
    self.driver.find_element(By.LINK_TEXT, "Top Rated").click()
    self.driver.find_element(By.LINK_TEXT, "Login").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys(self.data)
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys(self.data)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-dark").click()
    self.driver.find_element(By.LINK_TEXT, "Register").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys(self.data)
    self.driver.find_element(By.ID, "email").send_keys(f"{self.data}@wp.pl")
    self.driver.find_element(By.ID, "password").send_keys(self.data)
    self.driver.find_element(By.ID, "password2").send_keys(self.data)
    element = self.driver.find_element(By.XPATH, "/html/body/div/main/section/form/button")
    self.driver.execute_script("arguments[0].scrollIntoView();", element)
    time.sleep(2)
    element.click()
    time.sleep(2)
    self.driver.find_element(By.XPATH, "/html/body/nav/div/ul/li[1]/form/div/input").send_keys("avengers")
    self.driver.find_element(By.XPATH, "/html/body/nav/div/ul/li[1]/form/div/button").send_keys(Keys.ENTER)
    time.sleep(2)
    self.driver.find_element(By.XPATH, "/html/body/main/div/a[1]").click()
    time.sleep(2)
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.close()
  
